// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzd2CnNXyCtGJi60_69XmsWrzwYwdV9h4',
    appId: '1:343922145540:web:2190fcf84dace0c2aab851',
    messagingSenderId: '343922145540',
    projectId: 'pendopo-uti-d19f2',
    authDomain: 'pendopo-uti-d19f2.firebaseapp.com',
    storageBucket: 'pendopo-uti-d19f2.firebasestorage.app',
    measurementId: 'G-GTM5JG6ZXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjNYNZDjwtWjrVzAGTQ3BWtBzCWCE76BU',
    appId: '1:866130709002:android:53a566c7be571aeb302df3',
    messagingSenderId: '866130709002',
    projectId: 'pendopo-uti-c1bba',
    storageBucket: 'pendopo-uti-c1bba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUdd0_hTTzlZKGteu6DayffYRH1O5K5Zs',
    appId: '1:343922145540:ios:b5ffe8f2caef901caab851',
    messagingSenderId: '343922145540',
    projectId: 'pendopo-uti-d19f2',
    storageBucket: 'pendopo-uti-d19f2.firebasestorage.app',
    iosBundleId: 'com.example.pendopoUtiMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUdd0_hTTzlZKGteu6DayffYRH1O5K5Zs',
    appId: '1:343922145540:ios:b5ffe8f2caef901caab851',
    messagingSenderId: '343922145540',
    projectId: 'pendopo-uti-d19f2',
    storageBucket: 'pendopo-uti-d19f2.firebasestorage.app',
    iosBundleId: 'com.example.pendopoUtiMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzd2CnNXyCtGJi60_69XmsWrzwYwdV9h4',
    appId: '1:343922145540:web:facebc633ac92167aab851',
    messagingSenderId: '343922145540',
    projectId: 'pendopo-uti-d19f2',
    authDomain: 'pendopo-uti-d19f2.firebaseapp.com',
    storageBucket: 'pendopo-uti-d19f2.firebasestorage.app',
    measurementId: 'G-0VVC2DTQRN',
  );
}
